# -*- coding: utf-8 -*-
"""python(College Placement Analyzer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrAboyOB6YaixQ2wzM77NjdKJSxkZNEx

College Placement Analyzer
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/placement_data.csv")
df

df.head()

df.tail()

df.info()

#Check for missing values
print(df.isnull().sum())

print(df['Placed'].unique())

# Ensure Package column is numeric
df['Package'] = pd.to_numeric(df['Package'], errors='coerce')
df.info()

df['Company'] = df['Company'].fillna('None')
df

# Total students count
total_students = len(df)

# Only placed students filter
placed_students = df[df["Placed"] == "Yes"]

#  Placed students count
placed_count = len(placed_students)

# Placement percentage calculate
placement_percentage = (placed_count / total_students) * 100

# Result print करा
print("Total Students:", total_students)
print("Placed Students:", placed_count)
print("Overall Placement Percentage:", placement_percentage, "%")

# Branch-wise total students
branch_total = df.groupby("Branch")["Student_ID"].count()

# Branch-wise placed students
branch_placed = df[df["Placed"] == "Yes"].groupby("Branch")["Student_ID"].count()

#  Combine both into one DataFrame
branch_analysis = pd.DataFrame({
    "Total Students": branch_total,
    "Placed Students": branch_placed
})

#  Missing values fill
branch_analysis = branch_analysis.fillna(0)

# Placement percentage calculate

#  Placement % = (Placed Students / Total Students) × 100

branch_analysis["Placement Percentage"] = (
    branch_analysis["Placed Students"] / branch_analysis["Total Students"]
) * 100

print(branch_analysis)

branch_analysis["Placement Percentage"].plot(kind="bar",color="orange")

plt.title("Branch-wise Placement Percentage")
plt.xlabel("Branch")
plt.ylabel("Placement Percentage")
plt.ylim(0, 100)
plt.show()

# Only placed students
placed_df = df[df["Placed"] == "Yes"]

# Overall Average Package
average_package = placed_df["Package"].mean()

# Highest Package
highest_package = placed_df["Package"].max()

#  Branch-wise Average Package
branch_avg_package = placed_df.groupby("Branch")["Package"].mean()

#  Print Results
print("Average Package (Overall):", round(average_package, 2), "LPA")
print("Highest Package:", highest_package, "LPA")
print("\nBranch-wise Average Package:")
print(branch_avg_package.round(2))

branch_avg_package.plot(kind="bar",color="orange")

plt.title("Branch-wise Average Package")
plt.xlabel("Branch")
plt.ylabel("Average Package (LPA)")
plt.ylim(0, branch_avg_package.max() + 2)

plt.show()

# Year-wise total students
year_total = df.groupby("Year")["Student_ID"].count()

# Year-wise placed students
year_placed = df[df["Placed"] == "Yes"].groupby("Year")["Student_ID"].count()

#  Combine into one DataFrame
year_analysis = pd.DataFrame({
    "Total Students": year_total,
    "Placed Students": year_placed
})

# NaN values fill
year_analysis = year_analysis.fillna(0)

# Placement percentage calculate
year_analysis["Placement Percentage"] = (
    year_analysis["Placed Students"] / year_analysis["Total Students"]
) * 100

print(year_analysis)

plt.figure(figsize=(6,6))

years = year_analysis.index.astype(int)

plt.plot(
    years,
    year_analysis["Placement Percentage"],
    marker='o',
    linestyle="--",
    color="red",
    linewidth=2
)

plt.title("Year-wise Placement Percentage Trend")
plt.xlabel("Year")
plt.ylabel("Placement Percentage")
plt.ylim(0, 100)
plt.grid(True)

plt.xticks(years)


plt.show()

# Only placed students
placed_df = df[df["Placed"] == "Yes"]

#  Company-wise placed students count
company_hiring = placed_df.groupby("Company")["Student_ID"].count()

# Descending order  sort
company_hiring = company_hiring.sort_values(ascending=False)

print("Top Recruiters:")
print(company_hiring)

plt.figure()
company_hiring.plot(kind='bar', color = "orange")
plt.xlabel("Company")
plt.ylabel("Students Hired")
plt.title("Top Recruiters")
plt.show()